### PR TITLE
1.0.2 Introduce flow to allow user to migrate to new account

### PR DESCRIPTION
**Pull request by szeidner**
This PR introduces a flow which will ask the user if they've created that wallet via the Android app or imported an existing wallet seed from elsewhere. If the user has previously created that seed in the app, it tells them to generate and copy a new seed and provides UI for that and then allows them to send their balance to the new address. The following items have also been added in this PR:

- A SecureRandom implementation which mitigates the problems of Android's SecureRandom caveats for generating seeds
- Removal of ability to copy seed to clipboard as the Android clipboard is vulnerable to attacks http://www.cis.syr.edu/%7Ewedu/Research/paper/clipboard_attack_dimva2014.pdf

A video of the feature can be found here - https://www.reddit.com/r/nanocurrency/comments/8t1m5g/for_community_review_nano_wallet_for_android/

### CODE REVIEW

**Comment by zackshapiro** [comment]
@JohnChangUK Wanna take a quick once over on this if you have a moment?

**Comment by Copernikaus** [comment]
Everything got stuck. Feel like its a rep problem. Running the node through my own desktop.

**Comment by zackshapiro** [comment]
@Copernikaus can you explain further? How is this a problem with Android?

**Comment by JohnChangUK** [comment]
@zackshapiro Changes look great to me, keep up the work guys!

**Comment by Copernikaus** [comment]
@zackshapiro was my own stupidity. Colmy helped me already. Wallet works perfect now. No problems and instant work. Used my own node tho, will try some different reps. 

Thanks

**Comment by zackshapiro** [comment]
@JohnChangUK Thanks for taking a look!

@Copernikaus got it.

**Pull request merged**
