### PR TITLE
Added support for RFID point of sale (nanoblackbox.net)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Improved code quality with the latest update.

 - Cut down long methods into smaller ones where it made sense.
 - Renamed a constant into upper case
 - Made nicer comments
 - Indention should be good now I hope
 - Changed some variable names from variable_name to variableName
 - Removed TO DO's and unnecessary variables
 - Removed Nano Logo in the RFID fragment cause it showed twice 
 - spacing of ==

**Comment by icarusglider** [comment]
Obtaining the hardware needed to setup and test this addition.

**Comment by ghost** [comment]
@icarusglider 
Nice!
I will send you the pos software. Just need a short time to improve something minor in it.

**Comment by ghost** [comment]
@icarusglider
Have you gotten around to test it?

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.

**Pull request closed without merging**
